### ISSUE TITLE
build error on ubuntu

### ISSUE THREAD

**Issue by patricerosay** [apizee/ApiRTC-mobile#13]
I followed the instructions
but I ran into the error bellow.
I had the same issue after execution of the init.sh

Failed to install 'cordova-custom-config': CordovaError: Using "requireCordovaModule" to load non-cordova module "child_process" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/media/patrice/dev/dev/git/apizee-webrtc/ApiRTC-mobile/plugins/cordova-custom-config/hooks/resolveDependencies.js:6:20)
    at runScriptViaModuleLoader (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:181:32)
    at runScript (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:16)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:125:20
    at process._tickCallback (internal/process/next_tick.js:68:7)
Using "requireCordovaModule" to load non-cordova module "child_process" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by patricerosay** [comment]
cordova build android
Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.

**Comment by FredLuart** [comment]
It seems to be an error between your Cordova version and cordova-custom-config module
Can you try to upgrade the version of cordova-custom-config ? 
Check package.json versions definition

**Comment by patricerosay** [comment]
i've managed to make  it work after cleaning depedencies
